drop table camp_info ;
CREATE TABLE `camp_info` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `firstImageUrl` text ,
  `zipcode` char(7) ,
  `addr1` text ,
  `addr2` text ,
  `facltNm` text ,
  `lineIntro` text ,
  `intro` text ,
  `featureNm` text ,
  `lctCl` text ,
  `doNm` text ,
  `sigunguNm` text ,
  `allar` int(11) ,
  `gnrlSiteCo` int(11) ,
  `autoSiteCo` int(11) ,
  `glampSiteCo` int(11) ,
  `caravSiteCo` int(11) ,
  `indvdlCaravSiteCo` int(11) ,
  `glampInnerFclty` text ,
  `caravInnerFclty` text ,
  `trlerAcmpnyAt` char(1) ,
  `caravAcmpnyAt` char(1) ,
  `eqpmnLendCl` text ,
  `sbrsCl` text ,
  `sbrsEtc` text ,
  `posblFcltyCl` text ,
  `posblFcltyEtc` text ,
  `themaEnvrnCl` text ,
  `animalCmgCl` text ,
  `toiletCo` int(11) ,
  `swrmCo` int(11) ,
  `wtrplCo` int(11) ,
  `brazierCl` text ,
  `siteBottomCl1` int(11) ,
  `siteBottomCl2` int(11) ,
  `siteBottomCl3` int(11) ,
  `siteBottomCl4` int(11) ,
  `siteBottomCl5` int(11) ,
  `homepage` text ,
  `resveUrl` text ,
  `tel` varchar(15) ,
  `induty` text ,
  `mapX` double ,
  `mapY` double ,
  PRIMARY KEY (`idx`)
);
select * from camp_info;